// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEoic18HQ79bmPWBtSOZQOkxhjMEIy8M4',
    appId: '1:526149683823:web:dd4a839b6bff779ce3db9a',
    messagingSenderId: '526149683823',
    projectId: 'galirage-agi-4ec97',
    authDomain: 'galirage-agi-4ec97.firebaseapp.com',
    storageBucket: 'galirage-agi-4ec97.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO4Qhn09M30f5Iw4h_w9gUsOCzjIT7Ok0',
    appId: '1:526149683823:android:8d34462b65f1d532e3db9a',
    messagingSenderId: '526149683823',
    projectId: 'galirage-agi-4ec97',
    storageBucket: 'galirage-agi-4ec97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsI2eL4nOKwkv40UpSiZFDiqkWhHp7zP8',
    appId: '1:526149683823:ios:06a014d90fa42f86e3db9a',
    messagingSenderId: '526149683823',
    projectId: 'galirage-agi-4ec97',
    storageBucket: 'galirage-agi-4ec97.appspot.com',
    androidClientId: '526149683823-15dcc78t7qcelhhrias23rcof7s0k5gu.apps.googleusercontent.com',
    iosClientId: '526149683823-spmhp5teulk7m2gusd47nlrun8isnfur.apps.googleusercontent.com',
    iosBundleId: 'com.example.drawerAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsI2eL4nOKwkv40UpSiZFDiqkWhHp7zP8',
    appId: '1:526149683823:ios:5004519af058ba50e3db9a',
    messagingSenderId: '526149683823',
    projectId: 'galirage-agi-4ec97',
    storageBucket: 'galirage-agi-4ec97.appspot.com',
    androidClientId: '526149683823-15dcc78t7qcelhhrias23rcof7s0k5gu.apps.googleusercontent.com',
    iosClientId: '526149683823-8lg81lhgbe8utjtc30ml5hh2tn5k3dgi.apps.googleusercontent.com',
    iosBundleId: 'com.example.drawerAuth.RunnerTests',
  );
}
